# Generated by Django 3.2.25 on 2024-07-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
    ]
